name: Deploy Staging to Firebase Hosting
on:
  push:
    branches:
      - develop
jobs:
  build_and_deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RICK_AND_MORTY_1DAD6 }}
          channelId: staging
          projectId: rick-and-morty-1dad6
